apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter-service
  namespace: freddy-quispe-12-namespace
spec:
  type: NodePort
  ports:
    - port: 9216
      targetPort: 9216
      nodePort: 30092
  selector:
    app: mongo
