apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: freddy-quispe-12-namespace
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tian11qb/sebastian-front-react-vite-tailwind:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
