apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoreo
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
      protocol: TCP
      name: http
  selector:
    app: prometheus
